# POST http://localhost:3003/api/login
# Content-Type: application/json

# {
#   "username": "Alice",
#   "password": "Password1234"
# }


POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsaWNlIiwiaWQiOiI2MDgxNTkzZTkyNTdhNDAxOGVlMWU5NTYiLCJpYXQiOjE2MTkwOTM3MjB9.l764768FGU6wExak9TI9Ypvut8jJL2CBYeO7e05o5yY

{
  "title": "Example 2",
  "author": "Finn",
  "url": "example.com",
  "likes": 12,
  "user": "6081593e9257a4018ee1e956"
}